/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_fenetre_ajouter (void);
GtkWidget* create_fenetre_modifier (void);
GtkWidget* create_fenetre_supprimer (void);
GtkWidget* create_fenetre_rechercher (void);
GtkWidget* create_fenetre_gestion (void);
GtkWidget* create_fenetre_acceuil (void);
GtkWidget* create_fenetre_statistiques (void);
