/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fenetre_afficher (void)
{
  GtkWidget *fenetre_afficher;
  GtkWidget *fixed1;
  GtkWidget *treeview1;
  GtkWidget *label10;
  GtkWidget *retourner;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label11;
  GtkWidget *actualiser;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label40;

  fenetre_afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_afficher), _("affichage"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (fenetre_afficher), fixed1);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 640, 168);
  gtk_widget_set_size_request (treeview1, 712, 464);

  label10 = gtk_label_new (_("Liste des donneurs"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 816, 80);
  gtk_widget_set_size_request (label10, 273, 65);

  retourner = gtk_button_new ();
  gtk_widget_show (retourner);
  gtk_fixed_put (GTK_FIXED (fixed1), retourner, 640, 680);
  gtk_widget_set_size_request (retourner, 168, 48);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (retourner), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox3), label11, FALSE, FALSE, 0);

  actualiser = gtk_button_new ();
  gtk_widget_show (actualiser);
  gtk_fixed_put (GTK_FIXED (fixed1), actualiser, 1096, 680);
  gtk_widget_set_size_request (actualiser, 154, 45);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (actualiser), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox12), label40, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) retourner, "clicked",
                    G_CALLBACK (on_retourner_clicked),
                    NULL);
  g_signal_connect ((gpointer) actualiser, "clicked",
                    G_CALLBACK (on_actualiser_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_afficher, fenetre_afficher, "fenetre_afficher");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label10, "label10");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, retourner, "retourner");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image3, "image3");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label11, "label11");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, actualiser, "actualiser");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image12, "image12");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label40, "label40");

  return fenetre_afficher;
}

GtkWidget*
create_fenetre_ajouter (void)
{
  GtkWidget *fenetre_ajouter;
  GtkWidget *fixed2;
  GtkWidget *label2;
  GtkWidget *label5;
  GtkWidget *id;
  GtkWidget *nom;
  GtkWidget *prenom;
  GtkWidget *label4;
  GtkWidget *label6;
  GtkWidget *groupe;
  GtkWidget *ets;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *label3;
  GtkWidget *label46;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *male;
  GSList *male_group = NULL;
  GtkWidget *label47;
  GtkWidget *female;
  GtkWidget *ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label8;
  GtkWidget *drogue;
  GtkWidget *tattoo;
  GtkWidget *anemie;
  GtkWidget *piercing;
  GtkWidget *label54;
  GtkWidget *label7;
  GtkWidget *treeviewajout;
  GtkWidget *actualiserajout;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image26;
  GtkWidget *label77;
  GtkWidget *combomal;
  GtkWidget *retournerajout;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label9;
  GtkWidget *ajout_succ;

  fenetre_ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_ajouter), _("Ajouter"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (fenetre_ajouter), fixed2);

  label2 = gtk_label_new (_("Formulaire d'ajout d'un donneur"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 720, 104);
  gtk_widget_set_size_request (label2, 393, 49);

  label5 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 480, 352);
  gtk_widget_set_size_request (label5, 113, 33);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed2), id, 624, 232);
  gtk_widget_set_size_request (id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed2), nom, 624, 288);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed2), prenom, 624, 352);
  gtk_widget_set_size_request (prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  label4 = gtk_label_new (_("Nom\n"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 488, 296);
  gtk_widget_set_size_request (label4, 105, 25);

  label6 = gtk_label_new (_("Groupe"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 936, 232);
  gtk_widget_set_size_request (label6, 113, 33);

  groupe = gtk_entry_new ();
  gtk_widget_show (groupe);
  gtk_fixed_put (GTK_FIXED (fixed2), groupe, 1120, 232);
  gtk_widget_set_size_request (groupe, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (groupe), 8226);

  ets = gtk_entry_new ();
  gtk_widget_show (ets);
  gtk_fixed_put (GTK_FIXED (fixed2), ets, 1120, 296);
  gtk_widget_set_size_request (ets, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ets), 8226);

  jour_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed2), jour, 1088, 376);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed2), mois, 1248, 376);
  gtk_widget_set_size_request (mois, 60, 27);

  annee_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed2), annee, 1416, 376);
  gtk_widget_set_size_request (annee, 60, 27);

  label3 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 472, 224);
  gtk_widget_set_size_request (label3, 153, 41);

  label46 = gtk_label_new (_("maladie_freq"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed2), label46, 416, 424);
  gtk_widget_set_size_request (label46, 161, 33);

  label43 = gtk_label_new (_("mois"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed2), label43, 1184, 384);
  gtk_widget_set_size_request (label43, 49, 17);

  label44 = gtk_label_new (_("annee"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed2), label44, 1352, 384);
  gtk_widget_set_size_request (label44, 49, 17);

  label45 = gtk_label_new (_("sexe"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed2), label45, 1024, 456);
  gtk_widget_set_size_request (label45, 49, 17);

  male = gtk_radio_button_new_with_mnemonic (NULL, _("male"));
  gtk_widget_show (male);
  gtk_fixed_put (GTK_FIXED (fixed2), male, 1112, 456);
  gtk_widget_set_size_request (male, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (male), male_group);
  male_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (male));

  label47 = gtk_label_new (_("jour"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed2), label47, 1032, 384);
  gtk_widget_set_size_request (label47, 49, 17);

  female = gtk_radio_button_new_with_mnemonic (NULL, _("female"));
  gtk_widget_show (female);
  gtk_fixed_put (GTK_FIXED (fixed2), female, 1192, 456);
  gtk_widget_set_size_request (female, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (female), male_group);
  male_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (female));

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), ajouter, 624, 696);
  gtk_widget_set_size_request (ajouter, 170, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox1), label8, FALSE, FALSE, 0);

  drogue = gtk_check_button_new_with_mnemonic (_("drogue"));
  gtk_widget_show (drogue);
  gtk_fixed_put (GTK_FIXED (fixed2), drogue, 808, 616);
  gtk_widget_set_size_request (drogue, 118, 24);

  tattoo = gtk_check_button_new_with_mnemonic (_("tattoo"));
  gtk_widget_show (tattoo);
  gtk_fixed_put (GTK_FIXED (fixed2), tattoo, 808, 584);
  gtk_widget_set_size_request (tattoo, 118, 24);

  anemie = gtk_check_button_new_with_mnemonic (_("anemie"));
  gtk_widget_show (anemie);
  gtk_fixed_put (GTK_FIXED (fixed2), anemie, 664, 616);
  gtk_widget_set_size_request (anemie, 118, 24);

  piercing = gtk_check_button_new_with_mnemonic (_("piercing"));
  gtk_widget_show (piercing);
  gtk_fixed_put (GTK_FIXED (fixed2), piercing, 664, 584);
  gtk_widget_set_size_request (piercing, 118, 24);

  label54 = gtk_label_new (_("facteurs_de_risque"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed2), label54, 464, 592);
  gtk_widget_set_size_request (label54, 169, 49);

  label7 = gtk_label_new (_("Etablissement"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 904, 296);
  gtk_widget_set_size_request (label7, 185, 33);

  treeviewajout = gtk_tree_view_new ();
  gtk_widget_show (treeviewajout);
  gtk_fixed_put (GTK_FIXED (fixed2), treeviewajout, 1056, 496);
  gtk_widget_set_size_request (treeviewajout, 704, 328);

  actualiserajout = gtk_button_new ();
  gtk_widget_show (actualiserajout);
  gtk_fixed_put (GTK_FIXED (fixed2), actualiserajout, 1336, 840);
  gtk_widget_set_size_request (actualiserajout, 106, 37);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (actualiserajout), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image26 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox26), image26, FALSE, FALSE, 0);

  label77 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox26), label77, FALSE, FALSE, 0);

  combomal = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combomal);
  gtk_fixed_put (GTK_FIXED (fixed2), combomal, 600, 424);
  gtk_widget_set_size_request (combomal, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomal), _("HIV"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomal), _("Diabetique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomal), _("Tension"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomal), _("Maladie_Cardique"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (combomal), TRUE);

  retournerajout = gtk_button_new ();
  gtk_widget_show (retournerajout);
  gtk_fixed_put (GTK_FIXED (fixed2), retournerajout, 848, 696);
  gtk_widget_set_size_request (retournerajout, 138, 37);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (retournerajout), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox2), label9, FALSE, FALSE, 0);

  ajout_succ = gtk_label_new (_("as"));
  gtk_widget_show (ajout_succ);
  gtk_fixed_put (GTK_FIXED (fixed2), ajout_succ, 1352, 184);
  gtk_widget_set_size_request (ajout_succ, 313, 129);

  g_signal_connect ((gpointer) male, "toggled",
                    G_CALLBACK (on_male_toggled),
                    NULL);
  g_signal_connect ((gpointer) female, "toggled",
                    G_CALLBACK (on_female_toggled),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) drogue, "toggled",
                    G_CALLBACK (on_drogue_toggled),
                    NULL);
  g_signal_connect ((gpointer) tattoo, "toggled",
                    G_CALLBACK (on_tattoo_toggled),
                    NULL);
  g_signal_connect ((gpointer) anemie, "toggled",
                    G_CALLBACK (on_anemie_toggled),
                    NULL);
  g_signal_connect ((gpointer) piercing, "toggled",
                    G_CALLBACK (on_piercing_toggled),
                    NULL);
  g_signal_connect ((gpointer) treeviewajout, "row_activated",
                    G_CALLBACK (on_treeviewajout_row_activated),
                    NULL);
  g_signal_connect ((gpointer) actualiserajout, "clicked",
                    G_CALLBACK (on_actualiserajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) retournerajout, "clicked",
                    G_CALLBACK (on_retournerajout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_ajouter, fenetre_ajouter, "fenetre_ajouter");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label2, "label2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label5, "label5");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, id, "id");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, nom, "nom");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label4, "label4");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label6, "label6");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, groupe, "groupe");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, ets, "ets");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, jour, "jour");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, mois, "mois");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, annee, "annee");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label3, "label3");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label46, "label46");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label43, "label43");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label44, "label44");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label45, "label45");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, male, "male");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label47, "label47");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, female, "female");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, image1, "image1");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label8, "label8");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, drogue, "drogue");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, tattoo, "tattoo");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, anemie, "anemie");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, piercing, "piercing");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label54, "label54");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label7, "label7");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, treeviewajout, "treeviewajout");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, actualiserajout, "actualiserajout");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, image26, "image26");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label77, "label77");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, combomal, "combomal");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, retournerajout, "retournerajout");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, image2, "image2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label9, "label9");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, ajout_succ, "ajout_succ");

  return fenetre_ajouter;
}

GtkWidget*
create_fenetre_modifier (void)
{
  GtkWidget *fenetre_modifier;
  GtkWidget *fixed3;
  GtkWidget *fixed4;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *id;
  GtkWidget *nom;
  GtkWidget *prenom;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *groupe;
  GtkWidget *ets;
  GtkWidget *label12;
  GtkWidget *identifiant1;
  GtkWidget *label20;
  GtkWidget *modifier;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label18;
  GtkObject *jour1_adj;
  GtkWidget *jour1;
  GtkObject *mois1_adj;
  GtkWidget *mois1;
  GtkObject *annee1_adj;
  GtkWidget *annee1;
  GtkWidget *label52;
  GtkWidget *label53;
  GtkWidget *label49;
  GtkWidget *label48;
  GtkWidget *label51;
  GtkWidget *drogue1;
  GtkWidget *piercing1;
  GtkWidget *anemie1;
  GtkWidget *tattoo1;
  GtkWidget *facteurs_risques;
  GtkWidget *male1;
  GSList *male1_group = NULL;
  GtkWidget *female1;
  GtkWidget *treeviewmodif;
  GtkWidget *combomal1;
  GtkWidget *actualisermodif;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label76;
  GtkWidget *retournermodif;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label21;
  GtkWidget *modif_succ;

  fenetre_modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_modifier), _("Modifier"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (fenetre_modifier), fixed3);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_fixed_put (GTK_FIXED (fixed3), fixed4, 248, 168);
  gtk_widget_set_size_request (fixed4, 257, 16);

  label13 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 472, 224);
  gtk_widget_set_size_request (label13, 153, 41);

  label14 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 480, 352);
  gtk_widget_set_size_request (label14, 113, 33);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed4), id, 624, 232);
  gtk_widget_set_size_request (id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed4), nom, 624, 288);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed4), prenom, 624, 352);
  gtk_widget_set_size_request (prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  label15 = gtk_label_new (_("Nom\n"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 488, 296);
  gtk_widget_set_size_request (label15, 105, 25);

  label16 = gtk_label_new (_("Medecin Pr\303\251scripteur"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 904, 296);
  gtk_widget_set_size_request (label16, 185, 33);

  label17 = gtk_label_new (_("Groupe"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 936, 232);
  gtk_widget_set_size_request (label17, 113, 33);

  groupe = gtk_entry_new ();
  gtk_widget_show (groupe);
  gtk_fixed_put (GTK_FIXED (fixed4), groupe, 1120, 232);
  gtk_widget_set_size_request (groupe, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (groupe), 8226);

  ets = gtk_entry_new ();
  gtk_widget_show (ets);
  gtk_fixed_put (GTK_FIXED (fixed4), ets, 1120, 296);
  gtk_widget_set_size_request (ets, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ets), 8226);

  label12 = gtk_label_new (_("Formulaire de modification d'un donneur"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed4), label12, 712, 48);
  gtk_widget_set_size_request (label12, 393, 49);

  identifiant1 = gtk_entry_new ();
  gtk_widget_show (identifiant1);
  gtk_fixed_put (GTK_FIXED (fixed4), identifiant1, 624, 160);
  gtk_widget_set_size_request (identifiant1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (identifiant1), 8226);

  label20 = gtk_label_new (_("Donner l'identfiant de donneur \303\240 modifier"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 408, 160);
  gtk_widget_set_size_request (label20, 169, 25);

  modifier = gtk_button_new ();
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed4), modifier, 700, 570);
  gtk_widget_set_size_request (modifier, 200, 50);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (modifier), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox4), label18, FALSE, FALSE, 0);

  jour1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  jour1 = gtk_spin_button_new (GTK_ADJUSTMENT (jour1_adj), 1, 0);
  gtk_widget_show (jour1);
  gtk_fixed_put (GTK_FIXED (fixed3), jour1, 1384, 584);
  gtk_widget_set_size_request (jour1, 60, 27);

  mois1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  mois1 = gtk_spin_button_new (GTK_ADJUSTMENT (mois1_adj), 1, 0);
  gtk_widget_show (mois1);
  gtk_fixed_put (GTK_FIXED (fixed3), mois1, 1528, 584);
  gtk_widget_set_size_request (mois1, 60, 27);

  annee1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  annee1 = gtk_spin_button_new (GTK_ADJUSTMENT (annee1_adj), 1, 0);
  gtk_widget_show (annee1);
  gtk_fixed_put (GTK_FIXED (fixed3), annee1, 1672, 584);
  gtk_widget_set_size_request (annee1, 60, 27);

  label52 = gtk_label_new (_("mois"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed3), label52, 1464, 592);
  gtk_widget_set_size_request (label52, 49, 17);

  label53 = gtk_label_new (_("annee"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed3), label53, 1608, 592);
  gtk_widget_set_size_request (label53, 49, 17);

  label49 = gtk_label_new (_("sexe"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed3), label49, 1328, 672);
  gtk_widget_set_size_request (label49, 49, 17);

  label48 = gtk_label_new (_("maladie_freq"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed3), label48, 760, 600);
  gtk_widget_set_size_request (label48, 145, 25);

  label51 = gtk_label_new (_("jour"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed3), label51, 1304, 592);
  gtk_widget_set_size_request (label51, 49, 17);

  drogue1 = gtk_check_button_new_with_mnemonic (_("drogue"));
  gtk_widget_show (drogue1);
  gtk_fixed_put (GTK_FIXED (fixed3), drogue1, 1120, 704);
  gtk_widget_set_size_request (drogue1, 118, 24);

  piercing1 = gtk_check_button_new_with_mnemonic (_("piercing"));
  gtk_widget_show (piercing1);
  gtk_fixed_put (GTK_FIXED (fixed3), piercing1, 944, 672);
  gtk_widget_set_size_request (piercing1, 118, 24);

  anemie1 = gtk_check_button_new_with_mnemonic (_("anemie"));
  gtk_widget_show (anemie1);
  gtk_fixed_put (GTK_FIXED (fixed3), anemie1, 944, 704);
  gtk_widget_set_size_request (anemie1, 118, 24);

  tattoo1 = gtk_check_button_new_with_mnemonic (_("tattoo"));
  gtk_widget_show (tattoo1);
  gtk_fixed_put (GTK_FIXED (fixed3), tattoo1, 1120, 672);
  gtk_widget_set_size_request (tattoo1, 118, 24);

  facteurs_risques = gtk_label_new (_("facteurs_risques"));
  gtk_widget_show (facteurs_risques);
  gtk_fixed_put (GTK_FIXED (fixed3), facteurs_risques, 752, 664);
  gtk_widget_set_size_request (facteurs_risques, 161, 41);

  male1 = gtk_radio_button_new_with_mnemonic (NULL, _("male"));
  gtk_widget_show (male1);
  gtk_fixed_put (GTK_FIXED (fixed3), male1, 1408, 672);
  gtk_widget_set_size_request (male1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (male1), male1_group);
  male1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (male1));

  female1 = gtk_radio_button_new_with_mnemonic (NULL, _("female"));
  gtk_widget_show (female1);
  gtk_fixed_put (GTK_FIXED (fixed3), female1, 1496, 672);
  gtk_widget_set_size_request (female1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (female1), male1_group);
  male1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (female1));

  treeviewmodif = gtk_tree_view_new ();
  gtk_widget_show (treeviewmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), treeviewmodif, 16, 168);
  gtk_widget_set_size_request (treeviewmodif, 644, 376);

  combomal1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combomal1);
  gtk_fixed_put (GTK_FIXED (fixed3), combomal1, 936, 600);
  gtk_widget_set_size_request (combomal1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomal1), _("HIV"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomal1), _("Diabetique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomal1), _("Tension"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomal1), _("Maladie_Cardiaque"));

  actualisermodif = gtk_button_new ();
  gtk_widget_show (actualisermodif);
  gtk_fixed_put (GTK_FIXED (fixed3), actualisermodif, 240, 576);
  gtk_widget_set_size_request (actualisermodif, 122, 48);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (actualisermodif), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox25), label76, FALSE, FALSE, 0);

  retournermodif = gtk_button_new ();
  gtk_widget_show (retournermodif);
  gtk_fixed_put (GTK_FIXED (fixed3), retournermodif, 1416, 736);
  gtk_widget_set_size_request (retournermodif, 160, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (retournermodif), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox5), label21, FALSE, FALSE, 0);

  modif_succ = gtk_label_new (_("ms"));
  gtk_widget_show (modif_succ);
  gtk_fixed_put (GTK_FIXED (fixed3), modif_succ, 144, 680);
  gtk_widget_set_size_request (modif_succ, 281, 80);

  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) drogue1, "toggled",
                    G_CALLBACK (on_drogue1_toggled),
                    NULL);
  g_signal_connect ((gpointer) piercing1, "toggled",
                    G_CALLBACK (on_piercing1_toggled),
                    NULL);
  g_signal_connect ((gpointer) anemie1, "toggled",
                    G_CALLBACK (on_anemie1_toggled),
                    NULL);
  g_signal_connect ((gpointer) tattoo1, "toggled",
                    G_CALLBACK (on_tattoo1_toggled),
                    NULL);
  g_signal_connect ((gpointer) male1, "toggled",
                    G_CALLBACK (on_male1_toggled),
                    NULL);
  g_signal_connect ((gpointer) female1, "toggled",
                    G_CALLBACK (on_female1_toggled),
                    NULL);
  g_signal_connect ((gpointer) treeviewmodif, "row_activated",
                    G_CALLBACK (on_treeviewmodif_row_activated),
                    NULL);
  g_signal_connect ((gpointer) actualisermodif, "clicked",
                    G_CALLBACK (on_actualisermodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) retournermodif, "clicked",
                    G_CALLBACK (on_retournermodif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_modifier, fenetre_modifier, "fenetre_modifier");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label13, "label13");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label14, "label14");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, id, "id");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, nom, "nom");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label15, "label15");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label16, "label16");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label17, "label17");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, groupe, "groupe");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, ets, "ets");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label12, "label12");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, identifiant1, "identifiant1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label20, "label20");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image4, "image4");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label18, "label18");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, jour1, "jour1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, mois1, "mois1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, annee1, "annee1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label52, "label52");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label53, "label53");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label49, "label49");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label48, "label48");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label51, "label51");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, drogue1, "drogue1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, piercing1, "piercing1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, anemie1, "anemie1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, tattoo1, "tattoo1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, facteurs_risques, "facteurs_risques");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, male1, "male1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, female1, "female1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, treeviewmodif, "treeviewmodif");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, combomal1, "combomal1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, actualisermodif, "actualisermodif");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image25, "image25");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label76, "label76");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, retournermodif, "retournermodif");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image5, "image5");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label21, "label21");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, modif_succ, "modif_succ");

  return fenetre_modifier;
}

GtkWidget*
create_fenetre_supprimer (void)
{
  GtkWidget *fenetre_supprimer;
  GtkWidget *fixed5;
  GtkWidget *treeviewsupp;
  GtkWidget *actualisersupp;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image27;
  GtkWidget *label78;
  GtkWidget *fixed6;
  GtkWidget *identifiant1;
  GtkWidget *label23;
  GtkWidget *supprimer;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label30;
  GtkWidget *label22;
  GtkWidget *retournersupp;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label29;
  GtkWidget *supp_succ;

  fenetre_supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fenetre_supprimer, 300, 300);
  gtk_window_set_title (GTK_WINDOW (fenetre_supprimer), _("Supprimer"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (fenetre_supprimer), fixed5);

  treeviewsupp = gtk_tree_view_new ();
  gtk_widget_show (treeviewsupp);
  gtk_fixed_put (GTK_FIXED (fixed5), treeviewsupp, 120, 208);
  gtk_widget_set_size_request (treeviewsupp, 744, 520);

  actualisersupp = gtk_button_new ();
  gtk_widget_show (actualisersupp);
  gtk_fixed_put (GTK_FIXED (fixed5), actualisersupp, 432, 752);
  gtk_widget_set_size_request (actualisersupp, 194, 48);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (actualisersupp), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image27 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox27), image27, FALSE, FALSE, 0);

  label78 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (hbox27), label78, FALSE, FALSE, 0);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_fixed_put (GTK_FIXED (fixed5), fixed6, 296, 0);
  gtk_widget_set_size_request (fixed6, 0, 0);

  identifiant1 = gtk_entry_new ();
  gtk_widget_show (identifiant1);
  gtk_fixed_put (GTK_FIXED (fixed6), identifiant1, 816, 320);
  gtk_widget_set_size_request (identifiant1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (identifiant1), 8226);

  label23 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed6), label23, 624, 312);
  gtk_widget_set_size_request (label23, 153, 41);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed6), supprimer, 640, 472);
  gtk_widget_set_size_request (supprimer, 154, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox8), label30, FALSE, FALSE, 0);

  label22 = gtk_label_new (_("Formulaire de supression d'un donneur"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed6), label22, 632, 200);
  gtk_widget_set_size_request (label22, 393, 49);

  retournersupp = gtk_button_new ();
  gtk_widget_show (retournersupp);
  gtk_fixed_put (GTK_FIXED (fixed6), retournersupp, 1112, 464);
  gtk_widget_set_size_request (retournersupp, 138, 37);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (retournersupp), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox7), label29, FALSE, FALSE, 0);

  supp_succ = gtk_label_new (_("ss"));
  gtk_widget_show (supp_succ);
  gtk_fixed_put (GTK_FIXED (fixed5), supp_succ, 1120, 600);
  gtk_widget_set_size_request (supp_succ, 297, 104);

  g_signal_connect ((gpointer) treeviewsupp, "row_activated",
                    G_CALLBACK (on_treeviewsupp_row_activated),
                    NULL);
  g_signal_connect ((gpointer) actualisersupp, "clicked",
                    G_CALLBACK (on_actualisersupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) retournersupp, "clicked",
                    G_CALLBACK (on_retournersupp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_supprimer, fenetre_supprimer, "fenetre_supprimer");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, treeviewsupp, "treeviewsupp");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, actualisersupp, "actualisersupp");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, image27, "image27");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, label78, "label78");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, identifiant1, "identifiant1");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, label23, "label23");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, image8, "image8");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, label30, "label30");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, label22, "label22");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, retournersupp, "retournersupp");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, image7, "image7");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, label29, "label29");
  GLADE_HOOKUP_OBJECT (fenetre_supprimer, supp_succ, "supp_succ");

  return fenetre_supprimer;
}

GtkWidget*
create_fenetre_rechercher (void)
{
  GtkWidget *fenetre_rechercher;
  GtkWidget *fixed7;
  GtkWidget *fixed8;
  GtkWidget *identifiant1;
  GtkWidget *label32;
  GtkWidget *label31;
  GtkWidget *retourner_recherche;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label38;
  GtkWidget *treeviewrecherche;
  GtkWidget *actualiser_recherche;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image29;
  GtkWidget *label81;
  GtkWidget *recherche_succ;

  fenetre_rechercher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_rechercher), _("Rechercher"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (fenetre_rechercher), fixed7);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_fixed_put (GTK_FIXED (fixed7), fixed8, 24, 64);
  gtk_widget_set_size_request (fixed8, 0, 0);

  identifiant1 = gtk_entry_new ();
  gtk_widget_show (identifiant1);
  gtk_fixed_put (GTK_FIXED (fixed8), identifiant1, 536, 312);
  gtk_widget_set_size_request (identifiant1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (identifiant1), 8226);

  label32 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed8), label32, 336, 304);
  gtk_widget_set_size_request (label32, 153, 41);

  label31 = gtk_label_new (_("Formulaire de recherche  d'un donneur"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed8), label31, 536, 184);
  gtk_widget_set_size_request (label31, 393, 49);

  retourner_recherche = gtk_button_new ();
  gtk_widget_show (retourner_recherche);
  gtk_fixed_put (GTK_FIXED (fixed8), retourner_recherche, 816, 448);
  gtk_widget_set_size_request (retourner_recherche, 146, 45);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (retourner_recherche), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox10), label38, FALSE, FALSE, 0);

  treeviewrecherche = gtk_tree_view_new ();
  gtk_widget_show (treeviewrecherche);
  gtk_fixed_put (GTK_FIXED (fixed7), treeviewrecherche, 1040, 208);
  gtk_widget_set_size_request (treeviewrecherche, 776, 464);

  actualiser_recherche = gtk_button_new ();
  gtk_widget_show (actualiser_recherche);
  gtk_fixed_put (GTK_FIXED (fixed7), actualiser_recherche, 528, 504);
  gtk_widget_set_size_request (actualiser_recherche, 168, 56);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (actualiser_recherche), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image29 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox29), image29, FALSE, FALSE, 0);

  label81 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label81);
  gtk_box_pack_start (GTK_BOX (hbox29), label81, FALSE, FALSE, 0);

  recherche_succ = gtk_label_new (_("rs"));
  gtk_widget_show (recherche_succ);
  gtk_fixed_put (GTK_FIXED (fixed7), recherche_succ, 1264, 64);
  gtk_widget_set_size_request (recherche_succ, 369, 104);

  g_signal_connect ((gpointer) retourner_recherche, "clicked",
                    G_CALLBACK (on_retourner_recherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewrecherche, "row_activated",
                    G_CALLBACK (on_treeviewrecherche_row_activated),
                    NULL);
  g_signal_connect ((gpointer) actualiser_recherche, "clicked",
                    G_CALLBACK (on_actualiser_recherche_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_rechercher, fenetre_rechercher, "fenetre_rechercher");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, identifiant1, "identifiant1");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, label32, "label32");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, label31, "label31");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, retourner_recherche, "retourner_recherche");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, image10, "image10");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, label38, "label38");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, treeviewrecherche, "treeviewrecherche");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, actualiser_recherche, "actualiser_recherche");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, image29, "image29");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, label81, "label81");
  GLADE_HOOKUP_OBJECT (fenetre_rechercher, recherche_succ, "recherche_succ");

  return fenetre_rechercher;
}

GtkWidget*
create_fenetre_gestion (void)
{
  GtkWidget *fenetre_gestion;
  GtkWidget *fixed9;
  GtkWidget *treeviewaffiche;
  GtkWidget *label55;
  GtkWidget *statistiquesredirect;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label60;
  GtkWidget *supprimer_redirect;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label58;
  GtkWidget *modifier_redirect;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label57;
  GtkWidget *ajouter_redirect;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label56;
  GtkWidget *actualiser_gestion;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label61;
  GtkWidget *retourner_acceuil;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label62;
  GtkWidget *chercher_redirect;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label59;

  fenetre_gestion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_gestion), _("window1"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (fenetre_gestion), fixed9);

  treeviewaffiche = gtk_tree_view_new ();
  gtk_widget_show (treeviewaffiche);
  gtk_fixed_put (GTK_FIXED (fixed9), treeviewaffiche, 144, 136);
  gtk_widget_set_size_request (treeviewaffiche, 584, 280);

  label55 = gtk_label_new (_("Gestion Donneurs"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed9), label55, 368, 56);
  gtk_widget_set_size_request (label55, 257, 33);

  statistiquesredirect = gtk_button_new ();
  gtk_widget_show (statistiquesredirect);
  gtk_fixed_put (GTK_FIXED (fixed9), statistiquesredirect, 808, 368);
  gtk_widget_set_size_request (statistiquesredirect, 112, 48);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (statistiquesredirect), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("Statistiques"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox18), label60, FALSE, FALSE, 0);

  supprimer_redirect = gtk_button_new ();
  gtk_widget_show (supprimer_redirect);
  gtk_fixed_put (GTK_FIXED (fixed9), supprimer_redirect, 808, 256);
  gtk_widget_set_size_request (supprimer_redirect, 112, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (supprimer_redirect), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox16), label58, FALSE, FALSE, 0);

  modifier_redirect = gtk_button_new ();
  gtk_widget_show (modifier_redirect);
  gtk_fixed_put (GTK_FIXED (fixed9), modifier_redirect, 808, 200);
  gtk_widget_set_size_request (modifier_redirect, 112, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (modifier_redirect), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox15), label57, FALSE, FALSE, 0);

  ajouter_redirect = gtk_button_new ();
  gtk_widget_show (ajouter_redirect);
  gtk_fixed_put (GTK_FIXED (fixed9), ajouter_redirect, 808, 144);
  gtk_widget_set_size_request (ajouter_redirect, 104, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (ajouter_redirect), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox14), label56, FALSE, FALSE, 0);

  actualiser_gestion = gtk_button_new ();
  gtk_widget_show (actualiser_gestion);
  gtk_fixed_put (GTK_FIXED (fixed9), actualiser_gestion, 360, 440);
  gtk_widget_set_size_request (actualiser_gestion, 120, 48);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (actualiser_gestion), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox19), label61, FALSE, FALSE, 0);

  retourner_acceuil = gtk_button_new ();
  gtk_widget_show (retourner_acceuil);
  gtk_fixed_put (GTK_FIXED (fixed9), retourner_acceuil, 800, 432);
  gtk_widget_set_size_request (retourner_acceuil, 128, 48);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (retourner_acceuil), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox20), label62, FALSE, FALSE, 0);

  chercher_redirect = gtk_button_new ();
  gtk_widget_show (chercher_redirect);
  gtk_fixed_put (GTK_FIXED (fixed9), chercher_redirect, 808, 312);
  gtk_widget_set_size_request (chercher_redirect, 112, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (chercher_redirect), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox17), label59, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeviewaffiche, "row_activated",
                    G_CALLBACK (on_treeviewaffiche_row_activated),
                    NULL);
  g_signal_connect ((gpointer) statistiquesredirect, "clicked",
                    G_CALLBACK (on_statistiquesredirect_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_redirect, "clicked",
                    G_CALLBACK (on_supprimer_redirect_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_redirect, "clicked",
                    G_CALLBACK (on_modifier_redirect_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_redirect, "clicked",
                    G_CALLBACK (on_ajouter_redirect_clicked),
                    NULL);
  g_signal_connect ((gpointer) actualiser_gestion, "clicked",
                    G_CALLBACK (on_actualiser_gestion_clicked),
                    NULL);
  g_signal_connect ((gpointer) retourner_acceuil, "clicked",
                    G_CALLBACK (on_retourner_acceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) chercher_redirect, "clicked",
                    G_CALLBACK (on_chercher_redirect_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_gestion, fenetre_gestion, "fenetre_gestion");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, treeviewaffiche, "treeviewaffiche");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, label55, "label55");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, statistiquesredirect, "statistiquesredirect");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, image18, "image18");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, label60, "label60");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, supprimer_redirect, "supprimer_redirect");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, image16, "image16");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, label58, "label58");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, modifier_redirect, "modifier_redirect");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, image15, "image15");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, label57, "label57");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, ajouter_redirect, "ajouter_redirect");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, image14, "image14");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, label56, "label56");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, actualiser_gestion, "actualiser_gestion");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, image19, "image19");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, label61, "label61");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, retourner_acceuil, "retourner_acceuil");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, image20, "image20");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, label62, "label62");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, chercher_redirect, "chercher_redirect");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, image17, "image17");
  GLADE_HOOKUP_OBJECT (fenetre_gestion, label59, "label59");

  return fenetre_gestion;
}

GtkWidget*
create_fenetre_acceuil (void)
{
  GtkWidget *fenetre_acceuil;
  GtkWidget *fixed10;
  GtkWidget *label63;
  GtkWidget *image;
  GtkWidget *gestion_donneur;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label64;

  fenetre_acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_acceuil), _("window1"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (fenetre_acceuil), fixed10);

  label63 = gtk_label_new (_("We Donate "));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed10), label63, 648, 40);
  gtk_widget_set_size_request (label63, 313, 57);
  gtk_label_set_justify (GTK_LABEL (label63), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label63), 0.44, 0.5);

  image = create_pixmap (fenetre_acceuil, "don.jpg");
  gtk_widget_show (image);
  gtk_fixed_put (GTK_FIXED (fixed10), image, 280, 88);
  gtk_widget_set_size_request (image, 1072, 648);

  gestion_donneur = gtk_button_new ();
  gtk_widget_show (gestion_donneur);
  gtk_fixed_put (GTK_FIXED (fixed10), gestion_donneur, 120, 112);
  gtk_widget_set_size_request (gestion_donneur, 200, 224);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (gestion_donneur), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label64 = gtk_label_new_with_mnemonic (_("Gestion Des Donneurs"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox21), label64, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) gestion_donneur, "clicked",
                    G_CALLBACK (on_gestion_donneur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_acceuil, fenetre_acceuil, "fenetre_acceuil");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, label63, "label63");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, image, "image");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, gestion_donneur, "gestion_donneur");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, image21, "image21");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, label64, "label64");

  return fenetre_acceuil;
}

GtkWidget*
create_fenetre_statistiques (void)
{
  GtkWidget *fenetre_statistiques;
  GtkWidget *fixed11;
  GtkWidget *calendar1;
  GtkWidget *treeviewrdv;
  GtkWidget *entryjour;
  GtkWidget *entrymois;
  GtkWidget *entryan;
  GtkWidget *label65;
  GtkWidget *label69;
  GtkWidget *label66;
  GtkWidget *label68;
  GtkWidget *label67;
  GtkWidget *etablis;
  GtkWidget *label79;
  GtkWidget *nbrets;
  GtkWidget *moy;
  GtkWidget *valider;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label75;
  GtkWidget *label74;
  GtkWidget *label71;
  GtkWidget *afficherrdv;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label72;
  GtkWidget *retournerstat;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image28;
  GtkWidget *label80;

  fenetre_statistiques = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_statistiques), _("window1"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (fenetre_statistiques), fixed11);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed11), calendar1, 40, 80);
  gtk_widget_set_size_request (calendar1, 253, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  treeviewrdv = gtk_tree_view_new ();
  gtk_widget_show (treeviewrdv);
  gtk_fixed_put (GTK_FIXED (fixed11), treeviewrdv, 672, 24);
  gtk_widget_set_size_request (treeviewrdv, 696, 520);

  entryjour = gtk_entry_new ();
  gtk_widget_show (entryjour);
  gtk_fixed_put (GTK_FIXED (fixed11), entryjour, 496, 88);
  gtk_widget_set_size_request (entryjour, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryjour), 8226);

  entrymois = gtk_entry_new ();
  gtk_widget_show (entrymois);
  gtk_fixed_put (GTK_FIXED (fixed11), entrymois, 496, 136);
  gtk_widget_set_size_request (entrymois, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymois), 8226);

  entryan = gtk_entry_new ();
  gtk_widget_show (entryan);
  gtk_fixed_put (GTK_FIXED (fixed11), entryan, 496, 184);
  gtk_widget_set_size_request (entryan, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryan), 8226);

  label65 = gtk_label_new (_("Calendrier"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed11), label65, 88, 48);
  gtk_widget_set_size_request (label65, 160, 32);

  label69 = gtk_label_new (_("Liste des RDVS"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed11), label69, 400, 32);
  gtk_widget_set_size_request (label69, 137, 41);

  label66 = gtk_label_new (_("Entrer le jour\n"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed11), label66, 344, 96);
  gtk_widget_set_size_request (label66, 152, 24);

  label68 = gtk_label_new (_("Entrer le mois"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed11), label68, 368, 136);
  gtk_widget_set_size_request (label68, 113, 25);

  label67 = gtk_label_new (_("Entrer l'ann\303\251e"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed11), label67, 376, 184);
  gtk_widget_set_size_request (label67, 105, 25);

  etablis = gtk_entry_new ();
  gtk_widget_show (etablis);
  gtk_fixed_put (GTK_FIXED (fixed11), etablis, 496, 232);
  gtk_widget_set_size_request (etablis, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (etablis), 8226);

  label79 = gtk_label_new (_("Etablissement"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed11), label79, 360, 224);
  gtk_widget_set_size_request (label79, 129, 33);

  nbrets = gtk_label_new (_("nbrets"));
  gtk_widget_show (nbrets);
  gtk_fixed_put (GTK_FIXED (fixed11), nbrets, 1560, 104);
  gtk_widget_set_size_request (nbrets, 49, 17);

  moy = gtk_label_new (_("moy"));
  gtk_widget_show (moy);
  gtk_fixed_put (GTK_FIXED (fixed11), moy, 1568, 216);
  gtk_widget_set_size_request (moy, 49, 17);

  valider = gtk_button_new ();
  gtk_widget_show (valider);
  gtk_fixed_put (GTK_FIXED (fixed11), valider, 1528, 264);
  gtk_widget_set_size_request (valider, 120, 48);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (valider), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox24), label75, FALSE, FALSE, 0);

  label74 = gtk_label_new (_("La moyenne des RDVs par jour est :"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed11), label74, 1456, 160);
  gtk_widget_set_size_request (label74, 288, 64);

  label71 = gtk_label_new (_("Le nombre des \303\251tablissement est :"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed11), label71, 1440, 48);
  gtk_widget_set_size_request (label71, 288, 56);

  afficherrdv = gtk_button_new ();
  gtk_widget_show (afficherrdv);
  gtk_fixed_put (GTK_FIXED (fixed11), afficherrdv, 976, 568);
  gtk_widget_set_size_request (afficherrdv, 128, 56);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (afficherrdv), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label72 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox23), label72, FALSE, FALSE, 0);

  retournerstat = gtk_button_new ();
  gtk_widget_show (retournerstat);
  gtk_fixed_put (GTK_FIXED (fixed11), retournerstat, 1520, 552);
  gtk_widget_set_size_request (retournerstat, 130, 45);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (retournerstat), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image28 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox28), image28, FALSE, FALSE, 0);

  label80 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label80);
  gtk_box_pack_start (GTK_BOX (hbox28), label80, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeviewrdv, "row_activated",
                    G_CALLBACK (on_treeviewrdv_row_activated),
                    NULL);
  g_signal_connect ((gpointer) valider, "clicked",
                    G_CALLBACK (on_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficherrdv, "clicked",
                    G_CALLBACK (on_afficherrdv_clicked),
                    NULL);
  g_signal_connect ((gpointer) retournerstat, "clicked",
                    G_CALLBACK (on_retournerstat_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_statistiques, fenetre_statistiques, "fenetre_statistiques");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, treeviewrdv, "treeviewrdv");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, entryjour, "entryjour");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, entrymois, "entrymois");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, entryan, "entryan");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, label65, "label65");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, label69, "label69");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, label66, "label66");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, label68, "label68");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, label67, "label67");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, etablis, "etablis");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, label79, "label79");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, nbrets, "nbrets");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, moy, "moy");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, valider, "valider");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, image24, "image24");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, label75, "label75");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, label74, "label74");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, label71, "label71");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, afficherrdv, "afficherrdv");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, image23, "image23");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, label72, "label72");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, retournerstat, "retournerstat");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, image28, "image28");
  GLADE_HOOKUP_OBJECT (fenetre_statistiques, label80, "label80");

  return fenetre_statistiques;
}

