/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_loginUser (void);
GtkWidget* create_ajouterUser (void);
GtkWidget* create_updateUser (void);
GtkWidget* create_listUser (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_fenetre_ajouter (void);
GtkWidget* create_fenetre_modifier (void);
GtkWidget* create_fenetre_supprimer (void);
GtkWidget* create_fenetre_rechercher (void);
GtkWidget* create_fenetre_gestion (void);
GtkWidget* create_fenetre_acceuil (void);
GtkWidget* create_fenetre_statistiques (void);
GtkWidget* create_window_gestionfiche (void);
GtkWidget* create_window_ajfiche (void);
GtkWidget* create_window_modfiche (void);
GtkWidget* create_window_rechfiche (void);
GtkWidget* create_HOMEadmin (void);
GtkWidget* create_gestiondesetsislem (void);
GtkWidget* create_ajouterislem (void);
GtkWidget* create_Modifierislem (void);
GtkWidget* create_Supprimerislem (void);
GtkWidget* create_affichesuppressionislem (void);
GtkWidget* create_afficherislem (void);
GtkWidget* create_regcaptreeislem (void);
GtkWidget* create_loginislemadmin (void);
