/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

void set_text_in_layout(PangoLayout *layout, const gchar *text) {
    // Step 1: Ensure String is UTF-8
    if (!g_utf8_validate(text, -1, NULL)) {
        // Handle or fix the non-UTF-8 string
        g_print("Error: Invalid UTF-8 string.\n");
        return;
    }

    // Step 2: Handle Non-UTF-8 Characters
    gchar *sanitized_text = g_utf8_strup(text, -1); // Replace non-UTF-8 characters

    // Step 3: Debugging
    g_print("Debug: Text before setting in Pango layout: %s\n", text);

    // Set the sanitized text in the Pango layout
    pango_layout_set_text(layout, sanitized_text, -1);

    // Free the allocated memory
    g_free(sanitized_text);
}




int
main (int argc, char *argv[])
{

GtkWidget *fenetre_ajouter;
GtkWidget *fenetre_afficher;
GtkWidget *fenetre_modifier;
GtkWidget *fenetre_supprimer;
GtkWidget *fenetre_rechercher;
GtkWidget *fenetre_gestion;
GtkWidget *fenetre_acceuil;
GtkWidget *fenetre_statistiques;




 
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  //fenetre_ajouter = create_fenetre_ajouter ();
  //gtk_widget_show (fenetre_ajouter);
 //fenetre_afficher= create_fenetre_afficher ();
  //gtk_widget_show (fenetre_afficher);
 //fenetre_modifier= create_fenetre_modifier ();
  //gtk_widget_show (fenetre_modifier);
 //fenetre_supprimer= create_fenetre_supprimer ();
  //gtk_widget_show (fenetre_supprimer);
//fenetre_rechercher= create_fenetre_rechercher ();
  //gtk_widget_show (fenetre_rechercher);
//fenetre_gestion= create_fenetre_gestion ();
//gtk_widget_show (fenetre_gestion);
fenetre_acceuil= create_fenetre_acceuil ();
gtk_widget_show (fenetre_acceuil);
//fenetre_statistiques= create_fenetre_statistiques ();
//gtk_widget_show (fenetre_statistiques);
  gtk_main ();
  g_print("execution");
  return 0;
}

